{
  description = "Elixir development environment with mix2nix for reproducible builds";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    {
      nixpkgs,
      flake-utils,
      ...
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Elixir version (can be changed to elixir_1_16, elixir_1_15, etc.)
        beamPackages = pkgs.beam.packages.erlang;
        inherit (beamPackages) elixir;

        # Build Elixir application using mix2nix
        # First run: mix2nix > mix.nix (generates dependency manifest)
        # Then use the generated mix.nix for reproducible builds
        buildMixProject =
          {
            pname,
            version,
            src,
            mixEnv ? "prod",
            mixNix ? ./mix.nix,
            ...
          }@args:
          let
            # Load dependencies from mix.nix (generated by mix2nix)
            mixDeps = if builtins.pathExists mixNix then import mixNix { inherit beamPackages; } else [ ];
          in
          beamPackages.mixRelease (
            {
              inherit
                pname
                version
                src
                mixEnv
                ;

              # Dependencies from mix.nix
              inherit mixDeps;

              # Don't fetch deps at build time (use mixDeps instead)
              removeMixDeps = false;

              meta = with pkgs.lib; {
                description = "Elixir application built with Mix and mix2nix";
                platforms = platforms.unix;
              };
            }
            // builtins.removeAttrs args [
              "pname"
              "version"
              "src"
              "mixNix"
            ]
          );
      in
      rec {
        packages =
          let
            hasMixNix = builtins.pathExists ./mix.nix;
            omcSrc =
              if builtins.pathExists ./.omc then
                builtins.path {
                  path = ./.omc;
                  name = "omc-planning-artifacts";
                  filter =
                    path: _type:
                    let
                      rel = pkgs.lib.removePrefix (toString ./.omc + "/") path;
                    in
                    pkgs.lib.hasPrefix "plans/" rel
                    || pkgs.lib.hasPrefix "specs/" rel
                    || pkgs.lib.hasPrefix "research/" rel
                    || rel == "";
                }
              else
                null;
            mkGuideDocs =
              {
                includePlanning ? false,
              }:
              pkgs.stdenv.mkDerivation {
                name = "elixir-app-guide";
                src = ./docs;
                nativeBuildInputs = [ pkgs.mdbook ];
                buildPhase = ''
                  cp -r $src build-docs
                  chmod -R u+w build-docs
                  cd build-docs
                  ${pkgs.lib.optionalString (includePlanning && omcSrc != null) ''
                    chmod +x scripts/generate-planning-artifacts.sh
                    bash scripts/generate-planning-artifacts.sh ${omcSrc} src
                  ''}
                  mdbook build --dest-dir $out
                '';
                dontInstall = true;
              };
            apiDocs = beamPackages.mixRelease {
              pname = "elixir-app-docs";
              version = "0.1.0";
              src = ./.;
              mixEnv = "dev";
              mixDeps = import ./mix.nix { inherit beamPackages; };
              buildPhase = ''
                export MIX_HOME="$TMPDIR/.mix"
                mix docs
              '';
              installPhase = ''
                mkdir -p $out
                cp -r doc/. $out/
              '';
            };
            mkDoc =
              {
                includePlanning ? false,
              }:
              let
                guideDocs = mkGuideDocs { inherit includePlanning; };
              in
              if hasMixNix then
                pkgs.runCommand "elixir-app-doc" { } ''
                  mkdir -p $out/guide $out/api
                  cp -r ${guideDocs}/. $out/guide/
                  cp -r ${apiDocs}/. $out/api/
                ''
              else
                guideDocs;
          in
          {
            # Build the application as a release
            default = buildMixProject {
              pname = "elixir-app";
              version = "0.1.0";
              src = ./.;
              mixEnv = "prod";
              # mixNix = ./mix.nix;  # Uncomment after generating mix.nix
            };

            # Build documentation site.
            # Without mix.nix: mdBook guide only (result/index.html).
            # With mix.nix (including :ex_doc as a dev dep): combined guide/ + api/.
            # Run: nix run .#generate-mix-nix  (after adding ex_doc to mix.exs deps)
            doc = mkDoc { };

            # Like doc, but also includes active planning artifacts (.omc/plans, specs, research).
            doc-with-planning = mkDoc { includePlanning = true; };

            # Utility to generate mix.nix from mix.lock
            # Run: nix run .#generate-mix-nix
            generate-mix-nix = pkgs.writeShellScriptBin "generate-mix-nix" ''
              if [ ! -f mix.lock ]; then
                echo "Error: mix.lock not found. Run 'mix deps.get' first."
                exit 1
              fi

              echo "Generating mix.nix from mix.lock..."
              ${pkgs.mix2nix}/bin/mix2nix > mix.nix
              echo "✓ Generated mix.nix"
              echo ""
              echo "Next steps:"
              echo "  1. Commit mix.nix to version control"
              echo "  2. Uncomment 'mixNix = ./mix.nix;' in flake.nix packages.default"
              echo "  3. Run 'nix build' to build with locked dependencies"
            '';
          };

        # Development shell with Elixir tools
        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            # Elixir and Erlang
            elixir
            erlang

            # Hex and Rebar (required for dependencies, including GitHub repos)
            beamPackages.hex
            beamPackages.rebar3

            # mix2nix for generating mix.nix
            mix2nix

            # Development tools
            elixir-ls # Language server for IDE support
            git

            # Database clients (optional, uncomment if needed)
            # postgresql
            # sqlite

            # Additional tools
            inotify-tools # For file watching (Phoenix live reload)
            act # Run GitHub Actions locally

            # Local dev: secrets vault (OpenBao) + OIDC provider (Dex)
            openbao
            dex
          ];

          shellHook = ''
                        # Set up Mix directories
                        export MIX_HOME="$PWD/.nix-mix"
                        export HEX_HOME="$PWD/.nix-hex"
                        mkdir -p "$MIX_HOME" "$HEX_HOME"

                        # Add Mix binaries to PATH
                        export PATH="$MIX_HOME/bin:$HEX_HOME/bin:$PATH"

                        # Locale settings for Elixir
                        export LANG=C.UTF-8
                        export LC_ALL=C.UTF-8

                        echo "🧪 Elixir Development Environment (with mix2nix)"
                        echo "=============================================="
                        echo ""
                        echo "Elixir version: $(elixir --version | head -1)"
                        echo "Erlang/OTP: $(erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell)"
                        echo ""
                        echo "Quick commands:"
                        echo "  mix new <name>           - Create new Mix project"
                        echo "  mix deps.get             - Fetch dependencies"
                        echo "  mix compile              - Compile project"
                        echo "  mix test                 - Run tests"
                        echo "  mix test --cover         - Run tests with coverage"
                        echo "  mix format               - Format code"
                        echo "  mix credo                - Run static code analysis"
                        echo "  mix credo --strict       - Run strict analysis"
                        echo "  mix dialyzer             - Run type checker"
                        echo "  mix release              - Build release"
                        echo "  iex -S mix               - Start interactive shell"
                        echo ""
                        echo "mix2nix workflow:"
                        echo "  mix2nix > mix.nix        - Generate mix.nix from mix.lock"
                        echo "  nix run .#generate-mix-nix - Helper script to generate mix.nix"
                        echo ""
                        echo "Phoenix commands (if using Phoenix):"
                        echo "  mix phx.new <name>       - Create Phoenix project"
                        echo "  mix phx.server           - Start Phoenix server"
                        echo "  mix ecto.create          - Create database"
                        echo "  mix ecto.migrate         - Run migrations"
                        echo ""
                        echo "GitHub dependencies:"
                        echo "  Add to mix.exs: {:dep, github: \"user/repo\"}"
                        echo "  Then run: mix deps.get"
                        echo ""
                        echo "After adding/updating dependencies:"
                        echo "  1. mix deps.get          - Fetch new dependencies"
                        echo "  2. mix2nix > mix.nix     - Update Nix dependency manifest"
                        echo "  3. git add mix.nix       - Commit updated manifest"
                        echo ""

                        # Local dev: secrets vault (OpenBao) + OIDC provider (Dex)
                        export BAO_ADDR="''${BAO_ADDR:-http://127.0.0.1:8200}"
                        if [ ! -f .dev/dex.yaml ]; then
                          mkdir -p .dev
                          cat > .dev/dex.yaml.tmp <<'DEX_EOF'
            issuer: http://127.0.0.1:5556/dex
            storage:
              type: memory
            web:
              http: 127.0.0.1:5556
            staticClients:
              - id: dev-client
                redirectURIs:
                  - http://127.0.0.1:8080/callback
                name: Dev Client
                secret: dev-secret
            enablePasswordDB: true
            staticPasswords:
              - email: admin@example.com
                hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
                username: admin
                userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
            DEX_EOF
                          mv .dev/dex.yaml.tmp .dev/dex.yaml
                        fi
                        echo "Dev secrets: bao server -dev  (OpenBao on :8200)"
                        echo "Dev auth:    dex serve .dev/dex.yaml  (Dex OIDC on :5556)"
          '';
        };

        # App for running the built release
        apps = {
          default = flake-utils.lib.mkApp {
            drv = packages.default;
          };

          # Utility app to generate mix.nix
          generate-mix-nix = flake-utils.lib.mkApp {
            drv = packages.generate-mix-nix;
          };
        };
      }
    );
}
